# Generated by Django 5.0.4 on 2025-02-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crags',
            new_name='Crag',
        ),
    ]
