# Generated by Django 5.0.4 on 2025-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_report', '0002_rename_crags_crag'),
    ]

    operations = [
        migrations.AddField(
            model_name='crag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
